# Generated by Django 4.1.1 on 2022-12-10 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='whatchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='whatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
