# Generated by Django 4.1.1 on 2022-12-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_whatchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='whatchlist',
            new_name='watchlist',
        ),
    ]
